### ISSUE TITLE
sql_mode=only_full_group_by incompatibility

### ISSUE THREAD

**Issue by pacija** [gs11/sonerezh#1]
Hi,

I've just switched to this fork, and I'm getting the following issue when trying to access /albums page:

```
2017-05-23 16:10:47 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'underbottom_sonerezh.Song.cover' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /albums
Stack Trace:
#0 /usr/local/www/sonerezh-development-new/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /usr/local/www/sonerezh-development-new/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT MIN(`Son...', Array)
#2 /usr/local/www/sonerezh-development-new/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT MIN(`Son...', Array, Array)
#3 /usr/local/www/sonerezh-development-new/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT MIN(`Son...', Array)
#4 /usr/local/www/sonerezh-development-new/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Song), Array)
#5 /usr/local/www/sonerezh-development-new/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /usr/local/www/sonerezh-development-new/app/Controller/SongsController.php(314): Model->find('all', Array)
#7 [internal function]: SongsController->albums()
#8 /usr/local/www/sonerezh-development-new/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SongsController), Array)
#9 /usr/local/www/sonerezh-development-new/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /usr/local/www/sonerezh-development-new/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SongsController), Object(CakeRequest))
#11 /usr/local/www/sonerezh-development-new/app/webroot/index.php(107): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```
Could this be fixed in sonerezh code? I'd like to keep default sql_mode if possible:
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

**Comment by MightyCreak** [comment]
What are the advantages of using ONLY_FULL_GROUP_BY ?

**Comment by pacija** [comment]
I'm not much of a database guy, but from what I read, this default sql_mode was added recently, in mysql 5.7.5: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

For now I have retained default sql_mode minus ONLY_FULL_GROUP_BY by adding the following line to my.cnf and restarting mysql-server:
```
# added by pacija for sonerezh
sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```
/albums page now works for me. But perhaps sonerezh could be modified so it does SQL queries which are not disabled by default in current GA release?

Thank you in advance.

**Comment by gs11** [comment]
I guess this was an issue in Sonerezh even prior to my changes? If so I think the issue should be reported on the main project repo.

Anyway, if I understand this setting correctly it is because a selected field doesn't necessary be the same for all grouped rows which isn't legal for SQL-92.

From what I see in the code the issue seems to be the (translated) query:
`SELECT id, band, album, cover FROM songs GROUP BY album, band`

The non-aggregated fields id & cover are selected although they're not grouped by. I don't think id is used but for covers the query can be adjusted to use MAX(cover)

**Comment by gs11** [comment]
Reproduced the issue now and it is something that should be fixed to allow compatibility with mysql-5.7+ where this setting is default.

Did the fix directly in the development-new branch (https://github.com/gs11/sonerezh/commit/4558290ae5d25b324af8ed067a15b276f9b2bee6).
Please open an issue on the original project to make sure the change is done there as well.

**Comment by gs11** [comment]
@pacija I've moved to MySQL 5.7 here and it seems to be working fine but please verify on your end and close the issue if working.

**Comment by MightyCreak** [comment]
For what it worth, I've upgraded to this commit and tested (MySQL version: `mysql  Ver 14.14 Distrib 5.5.55, for debian-linux-gnu (x86_64) using readline 6.3`) and it works fine.

Soon I'll upgrade to Debian 9... soon... ;)

**Comment by pacija** [comment]
Works, thanks for the fix, closing the issue.

**Comment by gs11** [comment]
Last commit has a bugfix for the song removal process wasn't compatible with the sql mode.
