### ISSUE TITLE
show artist in player instead of band

### ISSUE THREAD

**Issue by pacija** [gs11/sonerezh#5]
Hi,

Currently player shows band when playing a track. This is fine with albums, but when playing compilations which have eg. "Various" as band, "Various" is what is shown next to track name.

In my opinion it would be better if artist is shown in player instead of band. Would it be too hard to change?

OT: I know I'm boring devs to death with my requests and that patches would be more welcome than just calling for attention regarding my problems and ideas, but unfortunately I'm no good in PHP.

**Comment by gs11** [comment]
This is a very valid change that I hadn't thought of myself. Should be minor, I'll look into it.

No worries, it was ~15 years since I last did something in PHP but nice to dig into this since I use sonerezh quite extensively myself.

**Comment by pacija** [comment]
Thank you, as "It is truly written: the best hacks start out as personal solutions to the author's everyday problems, and spread because the problem turns out to be typical for a large class of users." ~ [The Social Context of Open-Source Software](http://www.catb.org/esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s11.html)
:)

**Comment by gs11** [comment]
Fixed in latest commit of the development-new branch and PR submitted to the main repository.
