### ISSUE TITLE
Is it still safe to pull development-new?

### ISSUE THREAD

**Issue by MightyCreak** [gs11/sonerezh#8]
Hi!

I've been synchronizing with the development-new branch, since it has/had better features than the development branch from the original repo. But I'm looking at the [network graph](https://github.com/Sonerezh/sonerezh/network) from the original repo and it seems that all the modifications have been merged back into the main development branch.

Two questions:
- Do you still support this branch (i.e. development-new)?
- Could you merge Sonerezh/sonerezh/development into it, to see if the two branches are indeed in sync?

Cheers!

**Comment by MightyCreak** [comment]
I think you're just missing CakePHP 2.9.8..

**Comment by gs11** [comment]
Hi!

Sure, still working on it although there have just been a bugfix lately and no new features/fixes. I'll make sure to merge the official development branch into this. I need to work out what differences there are between my repo and the official one.
I'd hope that my PR https://github.com/Sonerezh/sonerezh/pull/300 gets merged as most of my other work depends on it but sadly no updates from the sonerezh team.

**Comment by gs11** [comment]
Development-new is now rebased with my development branch that's in sync with the official development branch. Hopefully all should be ok, I'm using it myself without any issues.
